<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
    </PropertyGroup>

    <ItemGroup>
      <Folder Include="Views\Shared\" />
      <Folder Include="wwwroot\lib\" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="Microsoft.EntityFrameworkCore.Sqlite" Version="8.0.0" />
      <PackageReference Include="Microsoft.EntityFrameworkCore.Tools" Version="8.0.0">
        <PrivateAssets>all</PrivateAssets>
        <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
      </PackageReference>
    </ItemGroup>

    <ItemGroup>
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\core.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\dist\jquery.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\dist\jquery.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\dist\jquery.min.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\jquery.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\jquery.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\jquery.min.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\jquery.slim.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\jquery.slim.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\jquery.slim.min.map" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery\LICENSE.txt" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation-unobtrusive\jquery.validate.unobtrusive.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation-unobtrusive\jquery.validate.unobtrusive.min.js" />
      <_ContentIncludedByDefault Remove="wwwroot\lib\jquery-validation-unobtrusive\LICENSE.txt" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ad.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ae.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\af.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ag.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ai.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\al.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\am.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ao.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\aq.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ar.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\as.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\au.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\aw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ax.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\az.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ba.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\bb.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\bd.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\be.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\bf.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\bg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\bh.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\bi.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\bj.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\bl.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\bm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\bn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\bo.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\bq.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\bs.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\bt.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\bv.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\bw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\by.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\bz.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\cc.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\cd.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\cf.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\cg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ch.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ci.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ck.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\cl.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\cm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\co.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\cr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\cu.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\cv.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\cw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\cx.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\cz.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\dj.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\dk.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\dm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\do.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\dz.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ec.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ee.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\eg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\eh.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\er.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\es.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\et.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\fj.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\fk.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\fm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\fo.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ga.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gb-eng.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gb-nir.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gb-sct.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gb-wls.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gd.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ge.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gf.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gh.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gi.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gl.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gp.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gq.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gs.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gt.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gu.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\gy.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\hk.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\hm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\hn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\hr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ht.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\hu.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\id.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ie.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\il.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\im.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\in.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\io.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\iq.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ir.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\is.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\je.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\jo.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ke.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\kg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\kh.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ki.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\km.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\kn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\kp.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\kr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\kw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ky.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\kz.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\la.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\lb.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\lc.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\li.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\lk.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\lr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ls.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\lt.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\lu.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\lv.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ly.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ma.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\mc.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\md.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\me.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\mf.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\mg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\mh.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\mk.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ml.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\mm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\mn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\mo.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\mp.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\mq.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\mr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ms.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\mt.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\mu.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\mv.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\mw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\my.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\mz.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\na.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\nc.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ne.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\nf.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ng.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ni.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\no.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\np.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\nr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\nu.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\nz.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\om.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\pa.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\pe.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\pf.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\pg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ph.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\pl.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\pm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\pn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\pr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ps.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\pw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\py.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\qa.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\re.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ro.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\rs.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\rw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\sa.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\sb.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\sc.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\sd.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\sg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\sh.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\si.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\sj.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\sl.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\sm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\sn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\so.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\sr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ss.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\st.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\sv.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\sx.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\sy.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\sz.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\tc.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\td.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\tf.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\tg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\tj.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\tk.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\tl.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\tm.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\tn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\to.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\tr.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\tt.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\tv.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\tw.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\tz.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ug.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\um.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\uz.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\va.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\vc.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ve.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\vg.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\vi.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\vn.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\vu.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\wf.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ws.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\xk.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\ye.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\yt.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\za.png" />
      <_ContentIncludedByDefault Remove="wwwroot\images\w160\zm.png" />
    </ItemGroup>

</Project>
