// <auto-generated />
using FirstResponsiveWebAppHey.Models.Olympics;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace FirstResponsiveWebAppHey.Migrations
{
    [DbContext(typeof(OlympicsContext))]
    partial class OlympicsContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.0");

            modelBuilder.Entity("FirstResponsiveWebAppHey.Models.Olympics.Category", b =>
                {
                    b.Property<string>("CategoryID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CategoryID");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryID = "indoor",
                            Name = "Indoor"
                        },
                        new
                        {
                            CategoryID = "outdoor",
                            Name = "Outdoor"
                        });
                });

            modelBuilder.Entity("FirstResponsiveWebAppHey.Models.Olympics.Country", b =>
                {
                    b.Property<string>("CountryID")
                        .HasColumnType("TEXT");

                    b.Property<string>("CategoryID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("GameID")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("LogoImage")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Sport")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("CountryID");

                    b.HasIndex("CategoryID");

                    b.HasIndex("GameID");

                    b.ToTable("Countries");

                    b.HasData(
                        new
                        {
                            CountryID = "can",
                            CategoryID = "indoor",
                            GameID = "winter",
                            LogoImage = "can.png",
                            Name = "Canada",
                            Sport = "Curling"
                        },
                        new
                        {
                            CountryID = "swe",
                            CategoryID = "indoor",
                            GameID = "winter",
                            LogoImage = "swe.png",
                            Name = "Sweden",
                            Sport = "Curling"
                        },
                        new
                        {
                            CountryID = "gbr",
                            CategoryID = "indoor",
                            GameID = "winter",
                            LogoImage = "gbr.png",
                            Name = "Great Britain",
                            Sport = "Curling"
                        },
                        new
                        {
                            CountryID = "jam",
                            CategoryID = "outdoor",
                            GameID = "winter",
                            LogoImage = "jam.png",
                            Name = "Jamaica",
                            Sport = "Bobsleigh"
                        },
                        new
                        {
                            CountryID = "ita",
                            CategoryID = "outdoor",
                            GameID = "winter",
                            LogoImage = "ita.png",
                            Name = "Italy",
                            Sport = "Bobsleigh"
                        },
                        new
                        {
                            CountryID = "jpn",
                            CategoryID = "outdoor",
                            GameID = "winter",
                            LogoImage = "jpn.png",
                            Name = "Japan",
                            Sport = "Bobsleigh"
                        },
                        new
                        {
                            CountryID = "ger",
                            CategoryID = "indoor",
                            GameID = "summer",
                            LogoImage = "ger.png",
                            Name = "Germany",
                            Sport = "Diving"
                        },
                        new
                        {
                            CountryID = "chn",
                            CategoryID = "indoor",
                            GameID = "summer",
                            LogoImage = "chn.png",
                            Name = "China",
                            Sport = "Diving"
                        },
                        new
                        {
                            CountryID = "mex",
                            CategoryID = "indoor",
                            GameID = "summer",
                            LogoImage = "mex.png",
                            Name = "Mexico",
                            Sport = "Diving"
                        },
                        new
                        {
                            CountryID = "bra",
                            CategoryID = "outdoor",
                            GameID = "summer",
                            LogoImage = "bra.png",
                            Name = "Brazil",
                            Sport = "Road Cycling"
                        },
                        new
                        {
                            CountryID = "ned",
                            CategoryID = "outdoor",
                            GameID = "summer",
                            LogoImage = "ned.png",
                            Name = "Netherlands",
                            Sport = "Cycling"
                        },
                        new
                        {
                            CountryID = "usa",
                            CategoryID = "outdoor",
                            GameID = "summer",
                            LogoImage = "usa.png",
                            Name = "USA",
                            Sport = "Road Cycling"
                        },
                        new
                        {
                            CountryID = "tha",
                            CategoryID = "indoor",
                            GameID = "paralympics",
                            LogoImage = "tha.png",
                            Name = "Thailand",
                            Sport = "Archery"
                        },
                        new
                        {
                            CountryID = "ury",
                            CategoryID = "indoor",
                            GameID = "paralympics",
                            LogoImage = "ury.png",
                            Name = "Uruguay",
                            Sport = "Archery"
                        },
                        new
                        {
                            CountryID = "ukr",
                            CategoryID = "indoor",
                            GameID = "paralympics",
                            LogoImage = "ukr.png",
                            Name = "Ukraine",
                            Sport = "Archery"
                        },
                        new
                        {
                            CountryID = "aut",
                            CategoryID = "outdoor",
                            GameID = "paralympics",
                            LogoImage = "aut.png",
                            Name = "Austria",
                            Sport = "Canoe Sprint"
                        },
                        new
                        {
                            CountryID = "pak",
                            CategoryID = "outdoor",
                            GameID = "paralympics",
                            LogoImage = "pak.png",
                            Name = "Pakistan",
                            Sport = "Canoe Sprint"
                        },
                        new
                        {
                            CountryID = "zwe",
                            CategoryID = "outdoor",
                            GameID = "paralympics",
                            LogoImage = "zwe.png",
                            Name = "Zimbabwe",
                            Sport = "Canoe Sprint"
                        },
                        new
                        {
                            CountryID = "fra",
                            CategoryID = "indoor",
                            GameID = "youth",
                            LogoImage = "fra.png",
                            Name = "France",
                            Sport = "Breakdancing"
                        },
                        new
                        {
                            CountryID = "cyp",
                            CategoryID = "indoor",
                            GameID = "youth",
                            LogoImage = "cyp.png",
                            Name = "Cyprus",
                            Sport = "Breakdancing"
                        },
                        new
                        {
                            CountryID = "rus",
                            CategoryID = "indoor",
                            GameID = "youth",
                            LogoImage = "rus.png",
                            Name = "Russia",
                            Sport = "Breakdancing"
                        },
                        new
                        {
                            CountryID = "fin",
                            CategoryID = "outdoor",
                            GameID = "youth",
                            LogoImage = "fin.png",
                            Name = "Finland",
                            Sport = "Skateboarding"
                        },
                        new
                        {
                            CountryID = "svk",
                            CategoryID = "outdoor",
                            GameID = "youth",
                            LogoImage = "svk.png",
                            Name = "Slovakia",
                            Sport = "Skateboarding"
                        },
                        new
                        {
                            CountryID = "prt",
                            CategoryID = "outdoor",
                            GameID = "youth",
                            LogoImage = "prt.png",
                            Name = "Portugal",
                            Sport = "Skateboarding"
                        });
                });

            modelBuilder.Entity("FirstResponsiveWebAppHey.Models.Olympics.Game", b =>
                {
                    b.Property<string>("GameID")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("GameID");

                    b.ToTable("Games");

                    b.HasData(
                        new
                        {
                            GameID = "summer",
                            Name = "Summer Olympics"
                        },
                        new
                        {
                            GameID = "winter",
                            Name = "Winter Olympics"
                        },
                        new
                        {
                            GameID = "paralympics",
                            Name = "Paralympics"
                        },
                        new
                        {
                            GameID = "youth",
                            Name = "Youth Olympic Games"
                        });
                });

            modelBuilder.Entity("FirstResponsiveWebAppHey.Models.Olympics.Country", b =>
                {
                    b.HasOne("FirstResponsiveWebAppHey.Models.Olympics.Category", "Category")
                        .WithMany()
                        .HasForeignKey("CategoryID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("FirstResponsiveWebAppHey.Models.Olympics.Game", "Game")
                        .WithMany()
                        .HasForeignKey("GameID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Category");

                    b.Navigation("Game");
                });
#pragma warning restore 612, 618
        }
    }
}
