// <auto-generated />
using ContactApp.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace ContactApp.Migrations
{
    [DbContext(typeof(ContactContext))]
    [Migration("20260223000801_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.23");

            modelBuilder.Entity("ContactApp.Models.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Note")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");

                    b.HasData(
                        new
                        {
                            ContactId = 1,
                            Address = "Somewhere in the world",
                            Name = "John",
                            Note = "",
                            PhoneNumber = "1123456789"
                        },
                        new
                        {
                            ContactId = 2,
                            Address = "Texas",
                            Name = "Jane",
                            Note = "",
                            PhoneNumber = "9908872432"
                        },
                        new
                        {
                            ContactId = 3,
                            Address = "Davenport Iowa",
                            Name = "Jake",
                            Note = "Works at State Farm",
                            PhoneNumber = "4523366412"
                        },
                        new
                        {
                            ContactId = 4,
                            Address = "California",
                            Name = "Dua",
                            Note = "Is a Singer",
                            PhoneNumber = "3334441234"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
